INSERT INTO `nav_page_template` VALUES (7, '抹茶', 'matcha', '抹茶影视', NOW(), NOW());

INSERT INTO `nav_zone` VALUES (13, '抹茶logo', 'matchaLogo', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (14, '抹茶横幅', 'matchaBanner', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (15, '抹茶应用', 'matchaAppList', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (16, '抹茶App启动图', 'matchaAppLaunch', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (17, '抹茶弹窗图', 'matchaDialog', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (18, '抹茶视频图', 'matchaVideo', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (19, '抹茶分享图', 'matchaShare', NOW(), NOW());
INSERT INTO `nav_zone` VALUES (22, '抹茶首页专区', 'matchaHomeZone', NOW(), NOW());

INSERT INTO `nav_ad_group` VALUES (21, '抹茶logo', '', 'matchaLogo', '[{\"name\":\"标题\",\"key\":\"title\"},{\"name\":\"公告\",\"key\":\"announcement\"},{\"name\":\"下载链接\",\"key\":\"link\"}]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (22, '抹茶横幅', '', 'matchaBanner', '[]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (23, '抹茶应用', '', 'matchaAppList', '[]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (24, '抹茶App启动图', '', 'matchaAppLaunch', '[]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (25, '抹茶弹窗图', '', 'matchaDialog', '[]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (26, '抹茶视频图', '', 'matchaVideo', '[]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (27, '抹茶分享图', '', 'matchaShare', '[{\"name\":\"链接\",\"key\":\"link\"}]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (30, '抹茶首页楼凤专区', '', 'matchaDateZone', '[{\"name\":\"文本1\",\"key\":\"text1\"},{\"name\":\"文本2\",\"key\":\"text2\"},{\"name\":\"数字范围，2个数逗号隔开\",\"key\":\"range\"}]', NOW(), NOW());
INSERT INTO `nav_ad_group` VALUES (31, '抹茶首页直播专区', '', 'matchaLiveZone', '[{\"name\":\"标签\",\"key\":\"tag\"},{\"name\":\"标题\",\"key\":\"title\"},{\"name\":\"文本1\",\"key\":\"text1\"},{\"name\":\"数字范围，2个数逗号隔开\",\"key\":\"range\"}]', NOW(), NOW());

INSERT INTO `nav_page_template_zone_relation` VALUES (48, 7, 13, 21, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (49, 7, 14, 22, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (50, 7, 15, 23, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (51, 7, 16, 24, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (52, 7, 17, 25, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (53, 7, 18, 26, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (54, 7, 19, 27, 1, 0);
INSERT INTO `nav_page_template_zone_relation` VALUES (66, 7, 22, 30, 1, 10);
INSERT INTO `nav_page_template_zone_relation` VALUES (67, 7, 22, 31, 1, 20);

INSERT INTO `nav_ad` VALUES (67, '抹茶logo', 'up', '/Init/Zone/13/logo.png', 'https://www.bilibili.com', '{\"21\":{\"title\":\"永久域名:mochaav.com\",\"announcement\":\"因为APP中含有成人内容，所以可能会出现“恶意软件”或“病毒软件”的提示。\",\"link\":\"https://mochaav.com\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (68, '抹茶分享图', 'up', '/Init/Zone/19/bg.png', 'https://www.bilibili.com', '{\"27\":{\"link\":\"https:\\/\\/www.bilibili.com\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (69, '抹茶楼凤1', 'up', '/Init/Zone/22/d1.png', 'https://www.bilibili.com', '{\"30\":{\"text1\":\"在校学生\",\"text2\":\"49人约过\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (70, '抹茶楼凤2', 'up', '/Init/Zone/22/d2.png', 'https://www.bilibili.com', '{\"30\":{\"text1\":\"人妻\",\"text2\":\"96人约过\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (71, '抹茶楼凤3', 'up', '/Init/Zone/22/d3.png', 'https://www.bilibili.com', '{\"30\":{\"text1\":\"护士\",\"text2\":\"248人约过\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (72, '抹茶楼凤4', 'up', '/Init/Zone/22/d4.png', 'https://www.bilibili.com', '{\"30\":{\"text1\":\"少妇\",\"text2\":\"452人约过\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (73, '抹茶直播1', 'up', '/Init/Zone/22/l1.png', 'https://www.bilibili.com', '{\"31\":{\"tag\":\"热门\",\"title\":\"1对1直播\",\"text1\":\"8038人在线\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (74, '抹茶直播2', 'up', '/Init/Zone/22/l2.png', 'https://www.bilibili.com', '{\"31\":{\"tag\":\"热门\",\"title\":\"在线喷水\",\"text1\":\"2612人在线\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (75, '抹茶直播3', 'up', '/Init/Zone/22/l3.png', 'https://www.bilibili.com', '{\"31\":{\"tag\":\"热门\",\"title\":\"在线调教\",\"text1\":\"3492人在线\"}}', 1, 0.0000, 1, 1, NOW(), NOW());
INSERT INTO `nav_ad` VALUES (76, '抹茶直播4', 'up', '/Init/Zone/22/l4.png', 'https://www.bilibili.com', '{\"31\":{\"tag\":\"热门\",\"title\":\"直播操逼\",\"text1\":\"7319人在线\"}}', 1, 0.0000, 1, 1, NOW(), NOW());

INSERT INTO `nav_ad_group_relation` VALUES (21, 67, 100);
INSERT INTO `nav_ad_group_relation` VALUES (22, 2, 10);
INSERT INTO `nav_ad_group_relation` VALUES (22, 3, 20);
INSERT INTO `nav_ad_group_relation` VALUES (23, 4, 10);
INSERT INTO `nav_ad_group_relation` VALUES (23, 5, 20);
INSERT INTO `nav_ad_group_relation` VALUES (23, 6, 30);
INSERT INTO `nav_ad_group_relation` VALUES (23, 7, 40);
INSERT INTO `nav_ad_group_relation` VALUES (23, 8, 50);
INSERT INTO `nav_ad_group_relation` VALUES (23, 9, 60);
INSERT INTO `nav_ad_group_relation` VALUES (23, 10, 70);
INSERT INTO `nav_ad_group_relation` VALUES (23, 11, 80);
INSERT INTO `nav_ad_group_relation` VALUES (23, 12, 90);
INSERT INTO `nav_ad_group_relation` VALUES (23, 13, 100);
INSERT INTO `nav_ad_group_relation` VALUES (23, 14, 110);
INSERT INTO `nav_ad_group_relation` VALUES (23, 15, 120);
INSERT INTO `nav_ad_group_relation` VALUES (23, 16, 130);
INSERT INTO `nav_ad_group_relation` VALUES (23, 17, 140);
INSERT INTO `nav_ad_group_relation` VALUES (23, 18, 150);
INSERT INTO `nav_ad_group_relation` VALUES (23, 19, 160);
INSERT INTO `nav_ad_group_relation` VALUES (24, 2, 100);
INSERT INTO `nav_ad_group_relation` VALUES (25, 2, 100);
INSERT INTO `nav_ad_group_relation` VALUES (26, 2, 100);
INSERT INTO `nav_ad_group_relation` VALUES (27, 68, 100);
INSERT INTO `nav_ad_group_relation` VALUES (30, 69, 10);
INSERT INTO `nav_ad_group_relation` VALUES (30, 70, 20);
INSERT INTO `nav_ad_group_relation` VALUES (30, 71, 30);
INSERT INTO `nav_ad_group_relation` VALUES (30, 72, 40);
INSERT INTO `nav_ad_group_relation` VALUES (31, 73, 10);
INSERT INTO `nav_ad_group_relation` VALUES (31, 74, 20);
INSERT INTO `nav_ad_group_relation` VALUES (31, 75, 30);
INSERT INTO `nav_ad_group_relation` VALUES (31, 76, 40);
